### ISSUE TITLE
Enable users to add their own event calendars

### ISSUE THREAD

**Issue by bezes** [sky-uk/anticipy#100]
Input could be in the following formats:
- dictionary format {'event_name': [event_dates_list]}
- list of dates format (here the name could be optional)

In both the above formats, the input dates could either be fully described (e.g. YYYY/MM/DD), or partially described (e.g. MM/DD, DD, etc.)

In case of _n_ different dates, the user should specify if the events would be _one_ event with the same weight applying in all dates, or _n_ events equal to the number of dates.

**Comment by capelastegui** [comment]
Calendar model added. It can now be added manually to the model list.

Missing features:
- Setting up a default calendar (e.g. UK  or US) so that it will be applied to all forecasts.
- Passing a calendar model to run_forecast()
- For each forecast run, check for applicability of the calendar model: need 1+ full years in the input date range, and there must be non-null data for every calendar event.

**Comment by capelastegui** [comment]
We also need further tests, and a lot of documentation. A calendar-specific tutorial would be nice. Open a separate issue for that.

**Comment by capelastegui** [comment]
Note for future improvement: we should probably make our outlier detection logic aware of calendar models, so that known holidays  or events don't get filtered out.
